name: Draft Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version à publier (ex: 0.2.0)'
        required: true
jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update version in pyproject.toml
        run: |
          sed -i \
            "s/^version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" pyproject.toml
      - name: Commit version bump
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "chore: bump version to v${{ github.event.inputs.version }}"
      - name: Push bump commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Create and push tag
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
